# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ticket_id', models.IntegerField(unique=True, verbose_name=b'Ticket number')),
                ('ticket_slug', models.CharField(max_length=30, unique=True, verbose_name=b'Ticket slug')),
                ('ticket_subject', models.CharField(max_length=512, verbose_name=b'Ticket subject')),
                ('ticket_department', models.CharField(max_length=64, verbose_name=b'Ticket department')),
                ('ticket_status', models.CharField(max_length=64, verbose_name=b'Ticket status')),
                ('ticket_activity', models.CharField(max_length=64, verbose_name=b'Ticket activity')),
                ('ticket_due', models.CharField(max_length=64, verbose_name=b'Ticket due')),
                ('ticket_owner', models.CharField(max_length=128, verbose_name=b'Ticket owner')),
                ('ticket_replier', models.CharField(max_length=128, verbose_name=b'Ticket owner')),
                ('ticket_email', models.CharField(max_length=256, verbose_name=b'Ticket email')),
                ('ticket_priority', models.CharField(max_length=64, verbose_name=b'Ticket priotiry')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
