# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0005_auto_20151214_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2015, 12, 14, 17, 55, 40, 951779)),
        ),
    ]
