# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observer', '0009_auto_20151214_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2015, 12, 14, 18, 10, 30, 311897)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
