# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0019_auto_20151215_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='default_view_mode',
            field=models.CharField(choices=[(b'view', b'View'), (b'edit', b'Edit')], default=b'view', max_length=128, verbose_name=b'Detault page view mode'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2015, 12, 15, 6, 53, 49, 59157)),
        ),
    ]
