# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0020_auto_20151215_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[(b'', b'All'), (b'support', b'\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb6\xd0\xba\xd0\xb0'), (b'admin', b'\xd0\x94\xd0\xb5\xd0\xb6\xd1\x83\xd1\x80\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb0\xd0\xb4\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80'), (b'director', b'\xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'), (b'finance', b'\xd0\xa4\xd0\xb8\xd0\xbd.\xd0\xbe\xd1\x82\xd0\xb4\xd0\xb5\xd0\xbb'), (b'abuse', b'\xd0\x96\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xb1\xd1\x8b'), (b'superadmin', b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x80\xd1\x88\xd0\xb8\xd0\xb9 \xd0\xb0\xd0\xb4\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2015, 12, 15, 9, 19, 16, 245143)),
        ),
    ]
